# Generated by Django 6.0 on 2025-12-15 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grado_academico', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('tecnico_superior', 'Técnico Superior'), ('tecnico_medio', 'Técnico Medio')], default='licenciatura', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='curricular.facultad')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='curricular.sede')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['sede', 'facultad', 'nombre'],
                'unique_together': {('facultad', 'sede', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RediseñoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(default=2025)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('suspendido', 'Suspendido')], default='en_proceso', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rediseños', to='curricular.carrera')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rediseños_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rediseño Curricular',
                'verbose_name_plural': 'Rediseños Curriculares',
                'ordering': ['-año', 'carrera'],
                'unique_together': {('carrera', 'año')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('medio_verificacion', models.TextField(blank=True, help_text='Descripción del medio de verificación')),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricular.fase')),
                ('rediseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='curricular.rediseñocurricular')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Fase',
                'verbose_name_plural': 'Seguimientos de Fases',
                'ordering': ['rediseño', 'fase__orden'],
                'unique_together': {('rediseño', 'fase')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoComisionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comision_academica/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('tamaño', models.IntegerField(help_text='Tamaño en bytes')),
                ('tipo_mime', models.CharField(max_length=100)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(limit_choices_to={'fase__codigo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='curricular.seguimientofase')),
            ],
            options={
                'verbose_name': 'Archivo Comisión Académica',
                'verbose_name_plural': 'Archivos Comisión Académica',
                'ordering': ['-subido_el'],
            },
        ),
    ]
